### ISSUE TITLE
New package for inclusion - matb33:collection-hooks

### ISSUE THREAD

**Issue by SimonSimCity** [Meteor-Community-Packages/organization#11]
## Package/project name & description

Extends Mongo.Collection with `before`/`after` hooks for `insert`, `update`, `remove`, `find`, and `findOne`.

Works across client, server or a mix. Also works when a client initiates a collection method and the server runs the hook, all while respecting the collection validators (allow/deny).

## Links
* [Atmosphere](https://atmospherejs.com/matb33/collection-hooks)
* [Github repository](https://www.github.com/matb33/meteor-collection-hooks)

## Current status of the project
 - [ ] Active
 - [ ] Maintained
 - [X] Abandoned

 ## Reasoning

Since @zimme called out for maintainers (https://github.com/matb33/meteor-collection-hooks/issues/253) ...

I'm willing to support this package for the short while we're using it in our project, but we're on the way to move it out. It would mostly be that I'll be reading on PRs others would send in and merge them, but I do not plan on active bug-fixing if no PR is provided.

Please give a 👍 if you want this package to be maintained.

**Comment by sebakerckhof** [comment]
I'm quite familiar with the code base (still have this PR https://github.com/matb33/meteor-collection-hooks/pull/248 ) and we're actively using it. So I could help with this one. But it will indeed be quite passive as well (reviewing PR's, making sure it keeps working with new Meteor versions, ...)

**Comment by evolross** [comment]
On the forums there are some who mentioned that native Node events could be an alternative to using this package. Any thoughts on that?  Is it just preference? Or is there a benefit to using Event based hooks versus this package?

**Comment by StorytellerCZ** [comment]
@evolross Can you link this discussion here?

**Comment by znewsham** [comment]
I would also like to contribute - I'm working on a modification to specify which fields to include when fetching the current/previous document. As we think this behaviour may be behind some of the performance issues we're facing

**Comment by copleykj** [comment]
I think this one could move forward. It's a highly used package and there is an open call for maintainers so I think it's a pretty good fit.

**Comment by StorytellerCZ** [comment]
We are moving the package over. I will add @znewsham @SimonSimCity @sebakerckhof and myself into a team that will manage this package once the transfer is complete.

**Comment by copleykj** [comment]
I've set up a project board to help track the progress of moving this package. This might be better done as a comment here with some markdown checkboxes... Let me know if you all think per package project boards are overkill for this.

https://github.com/orgs/Meteor-Community-Packages/projects/2

**Comment by KoenLav** [comment]
Great work on this; I'm also willing to contribute and familiar enough with the codebase.

**Comment by StorytellerCZ** [comment]
Current status:
- [ ] Moved / Forked
- [x] Team Created
- [x] Meteor Org Created
- [x] `communitypackages` org added as a maintainer

**Comment by copleykj** [comment]
Any updates here @StorytellerCZ?

**Comment by StorytellerCZ** [comment]
Send an email today. Will wait about a week and if I don't hear back or don't find a better communication chanell then we will have to fork.

**Comment by copleykj** [comment]
Awesome, thanks for the update.

**Comment by StorytellerCZ** [comment]
Transfer was successful:
https://github.com/Meteor-Community-Packages/meteor-collection-hooks

**Comment by evolross** [comment]
@StorytellerCZ Here’s a link to that discussion: https://forums.meteor.com/t/replacing-collection-hooks-and-callbacks-with-native-node-events/44355/4

**Comment by sebakerckhof** [comment]
@evolross  I don't really see how that discussion is relevant. Sure, you can use an event emitter, but you would still need to monkey patch the collections for it to always run and to have a way to pass in the previous object, the changed fields, ... And by that time you just end up with this package (if you look at the collection-hooks codebase you'll see it's not much more than just that) and you'll very likely have the same bugs/limitations.
