### ISSUE TITLE
New package for inclusion - tap:i18n

### ISSUE THREAD

**Issue by vparpoil** [Meteor-Community-Packages/organization#12]
## tap:i18n

tap-i18n is a Meteor package that provides a comprehensive i18n solution for Meteor apps and packages, with the goal of standardizing the way package developers internationalize their packages.

## Links
* [Atmosphere](https://atmospherejs.com/tap/i18n)
* [Github repository](https://github.com/TAPevents/tap-i18n)

## Current status of the project
 - [ ] Active
 - [ ] Maintained
 - [x] Abandoned

 ## Reasoning
This package is referenced in the [meteor guide](https://guide.meteor.com/ui-ux.html#i18n) as one of the 2 options available for i18n. It has proven it's stability and ease of use (100k app installs on atmosphere). It seems to me a great idea to move it here since it has not been updated in 3 years and some PR are still open there with dependencies updates.
Since we are using it in several production apps, I am willing to invest some of my time contributing and maintaining such fork.

**Comment by StorytellerCZ** [comment]
Great package, I agree that an update would be great, rewrite to ecmascript/Typescript and personally would love interoperability with things like react-intl (or at least the ability to take in the Message Format strings). tap-i18n-db inspired me for my own approach, so I'm willing to contribute on that.

**Comment by StorytellerCZ** [comment]
Still haven't heard back...

**Comment by benlavalley** [comment]
These are the two forks that would be good candidates to start with - tap-i18n completely re-built with Javascript instead of Coffeescript:
https://github.com/ExentriqLtd/tap-i18n
https://github.com/lucendio/tap-i18n

**Comment by StorytellerCZ** [comment]
@benlavalley Any of the authors continuing development/maintenance and/or interested in transferring?

**Comment by benlavalley** [comment]
@StorytellerCZ Absolutely! I'm thrilled you would ask. I haven't had to do much on my TAP:i18n package lately because it's been working quite reliably. If we have a better repot like the one you mentioned, perhaps I could look at any possible enhancements my fork has and contribute them there? Let me know.

**Comment by StorytellerCZ** [comment]
@benlavalley Noted, we will use your repo as a starting point for the code. Now let's see if we can get the package publishing transferred here so that we can continue from the original namespace. If not, then I would like to try something different, but one thing at a time.

**Comment by evolross** [comment]
Our Meteor 1.9 production app has to use a local hot-rod version of `tap:i18n` as the latest version still relies on the deprecated Meteor version of `aldeed:simple-schema` which has been replaced by by npm version `simpl-schema`. And we had to remove the `unittest` folder to get it to compile. 

@StorytellerCZ Have you/are you addressing these issues in your fork for Meteor 1.10?

**Comment by benlavalley** [comment]
> Our Meteor 1.9 production app has to use a local hot-rod version of `tap:i18n` as the latest version still relies on the deprecated Meteor version of `aldeed:simple-schema` which has been replaced by npm version `simpl-schema`. And we had to remove the `unittest` folder to get it to compile.
> 
> @StorytellerCZ Have you/are you addressing these issues in your fork for Meteor 1.10?

Part of my fork was an update from aldeed:simple-schema to npm simpl-schema. I also updated some other packages as well, particularly the dependency on i18next to go from 3.4.1-to 19.0.5.

**Comment by juliomac** [comment]
This is a pretty important package!
