### ISSUE TITLE
New package for inclusion - meteor-useraccounts suite

### ISSUE THREAD

**Issue by vparpoil** [Meteor-Community-Packages/organization#13]
## meteor-useraccounts
User Accounts is a suite of packages for the Meteor.js platform. It provides highly customizable user accounts UI templates for many different front-end frameworks. At the moment it includes forms for sign in, sign up, forgot password, reset password, change password, enroll account, and link or remove of many 3rd party services.

## Links
* [Atmosphere](https://atmospherejs.com/useraccounts/core)
* [Github repository](https://github.com/meteor-useraccounts/)

## Current status of the project
 - [ ] Active
 - [ ] Maintained
 - [x] Abandoned

 ## Reasoning
This project is referenced by the [meteor guide](https://guide.meteor.com/accounts.html#useraccounts) as best practice to handle UI, [but abandoned](https://github.com/meteor-useraccounts/core/issues/768)
Having a well-working user accounts suite was one of the great things about meteor at some point. Today, these packages are no longer maintained and people need to maintain forks of such projects to keep in line with dependencies updates. New comers won't benefit of these forks and I guess the guide walkthrough is difficult to follow for them.

I am willing to contribute to maintenance.

**Comment by StorytellerCZ** [comment]
Given the diversification of the front-end this is primarily something for Blaze users. If we could establish a group around Blaze then this would be great for it.

**Comment by vparpoil** [comment]
I think that a good part of atmosphere packages are Blaze centric and since Blaze is still referenced in the Guide as ["the easiest to learn and has the most full-stack Meteor packages"](https://guide.meteor.com/ui-ux.html#view-layers), I believe that Blaze packages should be included here and maintained by those in the community still using it.

In my mind, there are enough Blaze users that raised their hands in the kick off discussion to consider bringing in Blaze centric packages. 
The case of the meteor-useraccounts suite [was already proposed](https://github.com/Meteor-Community-Packages/organization/issues/1#issuecomment-472650066) in this dicusssion though

**Comment by vparpoil** [comment]
I bumped into a react version of the accounts UI : https://github.com/royGil/accounts-react which has been forked and is maintained here : https://github.com/day/accounts-react/
I though it was worth mentioning here if it moves forward

**Comment by StorytellerCZ** [comment]
Interesting. I'm thinking maybe creating a Blaze team here for interested people.

**Comment by StorytellerCZ** [comment]
OK, Blaze team created. Any volunteers who want to take on maintaining this package?

**Comment by vparpoil** [comment]
Hi @StorytellerCZ, I am willing be a maintainer for this package. We use it in production in many apps

**Comment by StorytellerCZ** [comment]
This is pretty big project. Should probably be its own sub-team under Blaze team if we could get enough members.
Would be nice if we could create directories for repositories at least for presentation purposes.

But with @mitar here (who is member of that GitHub org) the question is if at this point it wouldn't be more feasible to get new maintainers into the project rather than fork/copy it over here. We can keep it under the same organizational structure if needed.

**Comment by mitar** [comment]
Sadly I do not have any real permissions there. Has anyone contacted @splendido?

**Comment by splendido** [comment]
Hi guys!
...shame on me about the way I've abandoned the project, I know!
I'm not really happy about it too :-(

This said, I'd be really happy to give required permissions to people willing to maintain all those packages!
Just tell me one to get superpowers and you'll be all set...

Thanks for the poke, really appreciated!

**Comment by coagmano** [comment]
There's no shame in changing priorities. It's FOSS after all

I'd be happy to help maintain as well, I've requested to join the blaze team

**Comment by mitar** [comment]
@splendido Awesome! Let us organize things on our side here (this is a new community project to maintain Meteor packages) and will get back to you.

For others: do you think we should move packages here to this repository? Or manage them in their original organization? The advantage of the former is that there will be always somebody with permissions around.

**Comment by vparpoil** [comment]
I think having a single org will also create a stronger image for the community

**Comment by copleykj** [comment]
I'm personally in favor of keeping things simple and not having multiple orgs for us to try to manage. That being said, this adds quite a lot of potential work, and I'd like to get a showing of who's willing to commit time to these packages before we move forward.

**Comment by copleykj** [comment]
After looking into this a little more, I'm not sure this is a great idea. The scope of work here is pretty large and the original org already lists of 9 members, yet maintenance is non-existent.

**Comment by StorytellerCZ** [comment]
@splendido If you want you can give access to community packages and I can jump in once in a while to merge and publish the most pressing things, but right now I don't think we have enough people willing to effectively maintain such a huge project.

**Comment by splendido** [comment]
> @splendido If you want you can give access to community packages and I can jump in once in a while to merge and publish the most pressing things, but right now I don't think we have enough people willing to effectively maintain such a huge project.

@StorytellerCZ sure, sounds good! I've just invited both you and @filipenevola!

**Comment by StorytellerCZ** [comment]
@splendido great! Thanks! Can you also add me to the Atmosphere org so that I can publish new versions?

**Comment by filipenevola** [comment]
@StorytellerCZ you already have permissions to publish it.

But if the community doesn't want to really maintain it's probably better to keep it under compat org.

**Comment by vparpoil** [comment]
Hi @StorytellerCZ, 
Can you confirm you have access to the whole useraccounts project ? 
If so, I think it would be great to have a new version of useraccounts:unstyled compatible with last Meteor version. Here is the [pull request](https://github.com/meteor-useraccounts/unstyled/pull/7 )

**Comment by StorytellerCZ** [comment]
Sorry, but I don't have access to any make any merges or anything of that sort on GitHub, I'm just a member of the org. As for Atmosphere I don't see myself having access to the whole.

**Comment by vparpoil** [comment]
@splendido can you double check? It looks like something didn't worked as expected... Thanks a lot !

**Comment by filipenevola** [comment]
Hi, at least on the Meteor Software side we are going to keep putting these changes under meteor-compat org. It is easier for us to track all the issues in a single organization for compat packages.

**Comment by vparpoil** [comment]
Closing this issue now because meteor team decided to maintain the meteor-compat versions of the principal packages and we can contribute there if modifications are needed. Thanks !

**Comment by harryadel** [comment]
What's the status of this? Is useraccounts still being maintained at meteor-compat? I noticed the [latest commit](https://github.com/meteor-compat/useraccounts-core/commit/33417aaf3e2d4d9cf62ae3c78f406fdf4e1becda) was 6 months ago by @denihs who no longer works at Meteor AFAIK. Maybe we're ought to revive this and merge the latest changes done under meteor-compat into the original package then move it under MCP. What do you guys think?

I'd be willing to chip and help carry this over if all parties are agreed!

For now, I'm using useraccounts at a local project, so I'm going to pull meteor-compat version and continue my work over there until hopefully this is resolved so it can be all brought back to the original package under MCP.

cc @splendido @StorytellerCZ @denihs @filipenevola @vparpoil
