### ISSUE TITLE
New package for inclusion - kadira:flow-router

### ISSUE THREAD

**Issue by vparpoil** [Meteor-Community-Packages/organization#14]
## Kadira:flow-router
FlowRouter is a very simple router for Meteor. It does routing for client-side apps and does not handle rendering itself.

## Links
* [Atmosphere](https://atmospherejs.com/kadira/flow-router)
* [Github repository](https://github.com/kadirahq/flow-router/)

## Current status of the project
 - [ ] Active
 - [ ] Maintained
 - [x] Abandoned

 ## Reasoning
First class routing for meteor, abandoned with the leave of Arunoda. Recommended by the [Meteor Guide](https://guide.meteor.com/routing.html#flow-router). I know that [VeliovGroup](https://github.com/VeliovGroup/flow-router/) is maintaining it's own fork, but I haven't tested so far. I think one of these routers should be maintained by the community.

**Comment by StorytellerCZ** [comment]
I would prefer using the VeliovGroup fork and changing the guide. Given that Kadira stuff is completely abandoned we would have to create a new fork in order to publish things which would complicate things for uninitiated people even more.

**Comment by vparpoil** [comment]
My bad, a PR has been submitted to the guide : https://github.com/meteor/guide/pull/834
But hasn't been merged in more than a year...

**Comment by StorytellerCZ** [comment]
@vparpoil Hmm... we should push on that then.
