### ISSUE TITLE
Meteor Community Slack

### ISSUE THREAD

**Issue by copleykj** [Meteor-Community-Packages/organization#15]
So, first of all, I'd like to apologize for my lack of presence over the past few months. Life things have been crazy for a while and with limited time, code that pays ends up taking priority. Fortunately, it seems things may be starting to settle down for me a bit and I'd like to see this effort gain much more momentum. 

So far everyone has been doing a wonderful job, especially @StorytellerCZ. Now that I have a bit more time, hopefully, I can help substantially more and we can move things forward much more rapidly. Meteor is still a fantastic beast and it would be amazing if we could help to restore some of it's well deserved former glory.

In the interest of agility and progressing as quickly as possible, I've created a Slack workspace for us. GitHub is a wonderful platform, but it's not for quick communication and the lack of an official mobile client means it doesn't travel well for those of us that may be on the go. Everyone is welcome to join and discuss.

Hope to see all of you there. 

https://join.slack.com/t/meteor-community/shared_invite/enQtNzUxMTcwNzU0NzM4LWU1MTJmMzlkMTM4OTU5MTQ3NjU2NGU2NDU4MDdhMTUwZmY1NGRmOGNiOWQ0MWI5ZmU3OTY1ZGQyOTI3YTg5ODE

**Comment by StorytellerCZ** [comment]
Great timing, on my side things are getting a bit more crazy. :laughing:

**Comment by copleykj** [comment]
That's Ok. We are going to pick Meteor up and move it forward together.

**Comment by mitar** [comment]
I will just make a new PR after a long time to Meteor. :-)

**Comment by copleykj** [comment]
I guess we've all gotten busy :construction_worker_man:

**Comment by mitar** [comment]
BTW, this is a 3rd Slack related to "Meteor community" I am joining. :-)

**Comment by copleykj** [comment]
I guess it's a good thing that this one is legit 😆

**Comment by SimonSimCity** [comment]
Since we've established this as a channel for communication and added it to the readme, this ticket can be closed right? Just trying to keep this repo clean :)

**Comment by mitar** [comment]
Yes, thanks.
