### ISSUE TITLE
Link to Awesome Meteor

### ISSUE THREAD

**Issue by mitar** [Meteor-Community-Packages/organization#21]
We should probably link to [Awesome Meteor](https://github.com/urigo/awesome-meteor) as a resource and also get them to include a link to this organization.

Moreover, we should probably help them curate the list. I see some useful packages missing and some which are not really maintained anymore listed.

**Comment by vparpoil** [comment]
Should we add the [Awesome Blaze](https://github.com/arggh/awesome-blaze) list as well ?

**Comment by StorytellerCZ** [comment]
I'm all for it.
Where should we place these links? On our temporary page or in the readme?

**Comment by copleykj** [comment]
Let's put them in the readme for now and once the site progresses we can add them there as well.

**Comment by StorytellerCZ** [comment]
Added a link to the [website](https://meteorjs.community/).
