### ISSUE TITLE
New package for inclusion - coagmano:stylus

### ISSUE THREAD

**Issue by coagmano** [Meteor-Community-Packages/organization#23]
## Package/project name & description

A Stylus compiler forked off meteor:stylus and mquandalle:stylus.

Includes many common stylus plugins

## Links
* [Atmosphere](https://atmospherejs.com/coagmano/stylus)
* [Github repository](https://github.com/coagmano/meteor-stylus)

## Current status of the project
 - [ ] Active
 - [x] Maintained
 - [ ] Abandoned

 ## Reasoning
 
Happy to keep maintaining, but thought I should add it to community since it's recommended by the guide.

Already added publish permissions to `meteorcommunity`

**Comment by StorytellerCZ** [comment]
Since recommended by the guide, then let's move it over.

**Comment by coagmano** [comment]
It does need a little bit of love. V2 came with a big perf cost for import globbing that I never worked out.

Also thinking of publishing a version without all the plugins that is more a clean successor to MDG's stylus plugin. I'll wait till we settle on a common community namespace for that though

**Comment by copleykj** [comment]
Any updates on this?

**Comment by coagmano** [comment]
Now moved: https://github.com/Meteor-Community-Packages/meteor-stylus

But not yet updated

**Comment by copleykj** [comment]
Awesome. Do we have a Meteor org setup for this package yet?

- [x] Moved / Forked
- [x] Team Created
- [ ] Meteor Org Created and set as maintainer
- [ ] `communitypackages` org added as a maintainer

**Comment by copleykj** [comment]
This looks to be complete. Any objections to closing this?

**Comment by coagmano** [comment]
No objections!
