### ISSUE TITLE
New package for inclusion - tmeasday:check-npm-versions

### ISSUE THREAD

**Issue by mitar** [Meteor-Community-Packages/organization#27]
## Links
* https://atmospherejs.com/tmeasday/check-npm-versions
* https://github.com/tmeasday/check-npm-versions

## Current status of the project
 * Abandoned

 ## Reasoning

I think it is used a lot, there are also quite some issues still present.
 
 ## Progress
 - [x] Discussion finished
 - [x] Moved / Forked
 - [x] Team Created
 - [x] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere

**Comment by copleykj** [comment]
I think this is a good proposal... With 48K installs this year I think this should at lease have bug fixes.

**Comment by copleykj** [comment]
Do we have anyone willing to work on this?

**Comment by coagmano** [comment]
Yeah I can help with this one

**Comment by copleykj** [comment]
The ownership of the repo for this package was transferred to us last night by Tom. I'll finish getting everything in order this morning.
