### ISSUE TITLE
New package for inclusion - collection2

### ISSUE THREAD

**Issue by harryadelb** [Meteor-Community-Packages/organization#29]
## Links
* [Atmosphere](https://atmospherejs.com/aldeed/collection2)
* [Github repository](https://github.com/aldeed/meteor-collection2)

## Current status of the project

 * Abandoned

 ## Reasoning

Coupled with simpl-schema, this package provide a robust and consistent data layer. And, it's even recommended by the Meteor docs! 
 
 ## Progress
 - [x] Discussion finished
 - [x] Moved / Forked
 - [x] Team Created
 - [x] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere

cc @aldeed

**Comment by aldeed** [comment]
I'll work on transferring this one hopefully this week.

This one is not so much abandoned as it is complete and stable. It rarely needs any work and still works with latest Meteor and SimpleSchema versions afaik. But either way I don't use it much or have time to answer questions, so I'm happy to transfer.

**Comment by aldeed** [comment]
Started the transfer process

**Comment by aldeed** [comment]
There is an open collective for this repo. I'm not sure what the process is to transfer that or if I can, but I would gladly transfer. I don't think it ever received any money. I can also just shut it down.

https://opencollective.com/meteor-collection2

**Comment by harryadelb** [comment]
Is everything done? Should I close this issue? @StorytellerCZ @aldeed

**Comment by copleykj** [comment]
Created team and org now so everything should be in order for this to be closed.

**Comment by harryadelb** [comment]
Thank you @copleykj and @aldeed :)
