### ISSUE TITLE
Contributions to Meteor core

### ISSUE THREAD

**Issue by filipenevola** [Meteor-Community-Packages/organization#3]
Hi, I think we could use this space here to also think on how we can help on Meteor core. Is there anyone with access to release a new Meteor version unless Ben? I don't think so.

If we can elect one or two members from the Community with right access to do this we could avoid a community fork and we could start to work on PRs directly on Meteor. Of course MDG needs to agree on that.

Right now even if we work really hard on a PR we have no guarantee that this PR is going to be released and when it is going to be released. If we make this happen (access to release) we could create an organized way to prioritize demands like Java (JCP) including main companies using Meteor and community in these decisions.

As 35.1% replied on the survey that they are willing to help with money (and only 8.8% said no) maybe we could have some members working on these demands and being paid for it.

Let me know what you think

**Comment by SimonSimCity** [comment]
Before thinking about asking MDG for write-access, I'd rather actively start working on PRs. Ben has shown that he's more than willing to accept PRs if they're thought through and he even has offered write-access to zodem because he (by his PRs) has shown a deep understanding of the internals of the meteor project (https://github.com/meteor/meteor/pull/10454#issuecomment-468420944).

A good list of asked features approved by Ben starts here: https://github.com/meteor/meteor-feature-requests/issues?q=is%3Aissue+is%3Aopen+label%3Apull-requests-encouraged

My $0.02 ...

**Comment by filipenevola** [comment]
It's ok to not start asking access to release but as MDG is not actively planning Meteor's next steps we need to have some group of people/companies to vote and shape the future of Meteor.

What of these items are more important?
- Batching Oplog Entries & DDP messages
- Source maps in standard-minifier-js
- native async/await support
- Dead code elimination during minification does not prune module dependency graph.
- Indexes on Mini Mongo

It's hard to decide without a clear process in place.

If we could (1) prioritize these with interested parties, and (2) define how it should be implemented, and (3) collect money to pay community members to work on these prioritized topics, that would be great.

What are the companies using Meteor that should be included in the Community Process? Or do you have better ideas on how to proceed with these decisions?

The process that I'm suggesting is a simplification of Java Community Process (JCP) that works with voting, electing Expert Groups, etc for many years.

**Comment by KoenLav** [comment]
I think the Meteor feature requests repository should be cleaned up and receive some more attention (from both MDG and the community); I've volunteered to clean it up. 

Also I think we should focus on slimmening the core of Meteor first, before we start expanding it again (Cordova support, for instance, would be a great candidate to move over to the community).

I like the idea of providing financial support, but think we should first form a group and process to decide on priorities.

**Comment by distalx** [comment]
I stumble-upon this, and find this approach interesting for providing and organizing monetary base incentives to contributors.
`https://issuehunt.io/`
