### ISSUE TITLE
New package for inclusion - vsivsi:job-collection

### ISSUE THREAD

**Issue by mitar** [Meteor-Community-Packages/organization#30]
## Package/project name & description

job-collection is a powerful and easy to use job manager designed and built for Meteor.js. It solves the following problems (and more):

*    Schedule jobs to run (and repeat) in the future, persisting across server restarts
*    Create repeating jobs with complex schedules using Later.js. See demo here
*    Move work out of Meteor's single threaded event-loop
*    Enable work on computationally expensive jobs to run anywhere, on any number of machines
*    Track jobs and their progress, and automatically retry failed jobs
*    Easily build an admin UI to manage all of the above using Meteor's reactivity and UI good

## Links
* [Atmosphere](https://atmospherejs.com/vsivsi/job-collection)
* [Github repository](https://github.com/vsivsi/meteor-job-collection)

## Current status of the project
 * Abandoned

 ## Reasoning

I think this is the best background task package for Meteor, supporting many use cases.
 
 ## Progress
 - [x] Discussion finished
 - [ ] Moved / Forked
 - [ ] Team Created
 - [ ] Meteor Org Created and set as maintainer
 - [ ] `communitypackages` org added as a maintainer on Atmosphere

**Comment by StorytellerCZ** [comment]
Have you looked on jobs from Max Savin? https://github.com/msavin/SteveJobs

**Comment by StorytellerCZ** [comment]
Also I think at this point we need to get things moving on packages that we have move into the org before admitting any new packages.

**Comment by mitar** [comment]
We [have people interested in maintaining](https://github.com/vsivsi/meteor-job-collection/pull/268#issuecomment-533396720), and they are already doing that in their fork, so not sure why making it more official and organized would be a bad thing?

**Comment by LarsBuur** [comment]
vsivsi:job-collection is mature and heavily battle-tested, also already written in typescript.

**Comment by mitar** [comment]
> also already written in typescript.

You mean CoffeeScript? :-)

**Comment by LarsBuur** [comment]
Jep - corrected it :-)

**Comment by sebakerckhof** [comment]
@StorytellerCZ Last time I looked steve jobs package was lacking some features compared to jobs collection. Most notably jobs collection allows you to have work distributed amongst multiple servers and to have workers outside of Meteor. There's a package for pure nodejs workers or you can even have workers in any other language using a rest api to fetch jobs.

**Comment by vsivsi** [comment]
`job-collection` author here. I fully support transitioning this package into community support. I'm no longer doing any active Meteor development, so this just makes sense given that others are still actively using it and will to keep it going. 

I would hope to be able to similarly transition its sister package `file-colleciton`.
 
Sorry for being late to the discussion, I've been out of action with a terrible case of the flu for a couple of weeks.  Get those shots, it's awful!

**Comment by vsivsi** [comment]
A couple of wrinkles...  The job-collection package has dependencies on some more generic node-js libs.  

1) https://github.com/vsivsi/meteor-job is my own base library that enables pure node-js code to play with job-collection. But job-collection itself is also built on this, so it needs to somehow come along, even though it's not a pure Meteor package. 

2) https://github.com/oortcloud/node-ddp-client  The pure node-js DDP client (and everything _it_ depends on, eg. https://github.com/oortcloud/ejson) is required for pure node-js worker authentication and interoperability.

3) https://github.com/vsivsi/ddp-login  Which streamlines robust worker authorization flow.

There are probably more. The point being that just maintaining job-collection but neglecting these other pieces will probably lead to difficulty down the line, so be aware.

**Comment by SimonSimCity** [comment]
Any update on this? I've already created my own personal fork of this and am running it in production nowadays (https://atmospherejs.com/simonsimcity/job-collection). I'd like to get it back into a non-forked maintained stream.

But I'm also on @StorytellerCZ that we might have to do some research here to investigate on where the different job packages are good in and where the individual implementation falls short in. I'm all in for diversity, but it should be reasonable when to join which path.

**Comment by sebakerckhof** [comment]
We are also using the fork from @SimonSimCity in our main product for a while now.

**Comment by wildhart** [comment]
Just a note on this - I am using [my own fork/rewrite](https://atmospherejs.com/wildhart/jobs) of msavin/sjobs, mainly due to [this significant inefficiency](https://github.com/msavin/SteveJobs/issues/63) in sjobs which is WONTFIX (every new job type/queue you create results in a 3 second `setInterval` which hits the db - my app currently has 20 different job queues/types!).  Also, despite claiming to be multi-server, job queues cannot be paused across servers and paused jobs do not survive a server reboot.

My own version is much more efficient as it uses a single observer on the job queue instead of 20 db lookups every 3 seconds!  Mine can also persists paused job queues across multiple servers.

I haven't used job-collection and it looks awesome, but I personally would not recommend endorsing msavin/sjobs.  Having said that, I wouldn't endorse mine either because I haven't written tests for it!

**Comment by copleykj** [comment]
I think we can move ahead with this. Does someone want to take the lead on getting the repo transferred and setting up orgs, teams, and permissions?

**Comment by mitar** [comment]
Where are we about this one?

**Comment by copleykj** [comment]
@mitar If we have maintainers in place, feel free to move forward.

**Comment by mitar** [comment]
I think maybe we could share it between @SimonSimCity and me? I am still interested in it, but at the moment a bit low on time.

**Comment by SimonSimCity** [comment]
@mitar I could help with the initial setup, but I'm no longer working on a project requiring it, so I'm not all too eager investing much time into it.

**Comment by mitar** [comment]
Still planing. :-)

**Comment by mitar** [comment]
Unstale.

**Comment by holmrenser** [comment]
@mitar, I am using a copied version of job-collection as a local package at the moment, but a community-hosted package would have my preference. I can help out from time to time.

**Comment by holmrenser** [comment]
Not stale from my perspective

**Comment by StorytellerCZ** [comment]
The setup is no problem. @mitar and @holmrenser if you want to become the maintainers on this then that is enough for me to get this started.

**Comment by holmrenser** [comment]
Sure thing! Let me know what I can do!

**Comment by holmrenser** [comment]
Proposal: @mitar and myself become maintainers, we put some (limited) effort into migrating this to meteor-community-packages as is. Afterwards we can think about updates/changes and review pull requests. I have a few modifications that might be interesting to include, but we can think about that once this is safely incorporated into meteor-community-packages.

@StorytellerCZ what do you think?

**Comment by holmrenser** [comment]
Not stale. Pinging @mitar and @StorytellerCZ

**Comment by holmrenser** [comment]
@StorytellerCZ Reminder

**Comment by StorytellerCZ** [comment]
Alright, first step is to add `communitypackages` to the package on Atmosphere and then we can start on the migration.

**Comment by StorytellerCZ** [comment]
On another note, we can now also migrate in: https://github.com/percolatestudio/meteor-synced-cron
