### ISSUE TITLE
Group or core maintainers on NPM

### ISSUE THREAD

**Issue by mitar** [Meteor-Community-Packages/organization#31]
Some Meteor packages also have NPM counter parts, so we would need permissions to publish new versions there as well.

Is there a way to have a group of users one can add to give them permissions on any package?

**Comment by StorytellerCZ** [comment]
I can create an npm organization with similar settings like on Atmoshpere, but I'm not sure about adding existing packages to it. From a quick look it should be possible.

**Comment by mitar** [comment]
Can you try to name it the same?

**Comment by StorytellerCZ** [comment]
What do you mean? `communitypackages` for the name of the group? I was thinking just `@mcp`.

**Comment by mitar** [comment]
Yes, `communitypackages`. But sure, we can also have some other group name there.

**Comment by StorytellerCZ** [comment]
I think since that is npm, `communitypackages` would not make sense there. So abbreviation should be fine.

**Comment by StorytellerCZ** [comment]
:thinking: Someone already has `@mcp` and it looks abandoned and completely unrelated. So maybe something more verbose?

**Comment by StorytellerCZ** [comment]
We could do `meteor-community`.

**Comment by StorytellerCZ** [comment]
Here it is: https://www.npmjs.com/org/meteor-community

**Comment by mitar** [comment]
Can you also add it to README, to mention that if there are related NPM packages, then we should do the same thing as for Atmosphere: create pacakge-specific group and add both package-specific group and backup group to the package to maintain it?

**Comment by StorytellerCZ** [comment]
On it.
