### ISSUE TITLE
New package for inclusion - meteor-slingshot

### ISSUE THREAD

**Issue by distalx** [Meteor-Community-Packages/organization#34]
## Package/project name & description

meteor-slingshot
Direct and secure file-uploads to AWS S3, Google Cloud Storage and others.

## Links
* [Atmosphere](https://atmospherejs.com/edgee/slingshot)
* [Github repository](https://github.com/CulturalMe/meteor-slingshot/)
* [Project homepage](https://github.com/CulturalMe/meteor-slingshot/)

## Current status of the project

 * Abandoned

 ## Reasoning

This package has a unique feature of letting upload files to s3 from client side. And it's fairly simple to use than other alternatives. It still being used by many people. (installs count is 48,062 on atmospherejs)

 ## Progress
 - [ ] Discussion finished
 - [ ] Moved / Forked
 - [x] Team Created
 - [ ] Meteor Org Created and set as maintainer
 - [ ] `communitypackages` org added as a maintainer on Atmosphere

CC @CaptainN

**Comment by harryadelb** [comment]
Isn't this already achievable with ostrio:files?

**Comment by vparpoil** [comment]
ostrio:files is indeed the reference package now to handle files but it doesn't enable (afaik) direct upload to third party cloud storage from the client. 
Maybe you could raise an issue over there to discuss the point first ?

**Comment by dr-dimitru** [comment]
@CaptainN 

> I do have at least one project that will likely always use slingshot

Totally understood as it serves different purpose, out of the `ostrio:files` bounds

> I'll probably migrate my apps to ostrio:files at some point

🥳

**Comment by distalx** [comment]
Revisiting this.

Found a maintained forked of this package.
https://github.com/Back2bikes/meteor-slingshot

cc @StorytellerCZ, @mikkelking

**Comment by harryadel** [comment]
Great suggestion @distalx, they're already looking for maintainers and it's much updated than the original slingshot. Maybe we can fork theirs and assign @mikkelking as part of the team so he may directly contribute too.
https://github.com/Back2bikes/meteor-slingshot#looking-for-maintainers
