### ISSUE TITLE
New package for inclusion - Ground:DB

### ISSUE THREAD

**Issue by CaptainN** [Meteor-Community-Packages/organization#35]
## Links
* [Atmosphere](https://atmospherejs.com/ground/db)
* [GitHub](https://github.com/GroundMeteor/db)

## Current status of the project
 * Abandoned?

 ## Reasoning
It's incredibly useful for offline collections. I'm using it in `npdev:collections` and am happy to maintain it. It could use some updates and additions:
- Remove underscore, and update localforage (I already have a PR in for that)
- Add support for SSR
- Add support for Collection2 for offline only collections
 
 ## Progress
 - [x] Discussion finished
 - [ ] Moved / Forked
 - [x] [Team Created](https://github.com/orgs/Meteor-Community-Packages/teams/databases)
 - [ ] Meteor Org Created and set as maintainer
 - [ ] `communitypackages` org added as a maintainer on Atmosphere

**Comment by dr-dimitru** [comment]
Hello @CaptainN ,

Great suggestion, as this package was used in some of our projects, but due to it was abandoned we started working on our own implementation of "Persistent-Collection". It isn't out yet but should be published within a month. Not saying it would replace GroundDB, but definitely will serve the need of having a "Persistent-Collection" on the *Client* (Browser/Cordova).

**Comment by CaptainN** [comment]
I reached out to @raix in [a ticket](https://github.com/GroundMeteor/db/issues/212), and he indicated receptiveness to migrating the package, to get some additional maintainers. I think we need to discuss with him yet, how to do that (I'm not 100% clear on that myself). Next steps would be moving things over.

**Comment by StorytellerCZ** [comment]
Created Databases team to handle this and any other future projects with databases.

**Comment by mikkelking** [comment]
Sounds like a great idea, would be interested in lending a hand

**Comment by CaptainN** [comment]
I still intend to move this, and got permission. I'm just not sure what to do next...

**Comment by copleykj** [comment]
Looks like @raix is already a member so he should be able to just move the repo and add the maintainer at his discretion

**Comment by CyberCyclone** [comment]
I take it that this hasn't been migrated yet or forked? I've found this forked version (https://atmospherejs.com/settlin/ground-db) however I'd prefer to use an official version.

**Comment by copleykj** [comment]
@CyberCyclone no, it has not. My guess is that @CaptainN has been quite busy with other things. I'll reopen this and maybe we can move forward with this.

**Comment by CaptainN** [comment]
Yes, I dropped this, and haven't been able to find the time to pick it back up. The package doesn't need a ton of maintenance, just some package updates and releases. Hopefully someone can pick it up and run with it.

**Comment by raix** [comment]
I'll try to get the repos moved to the community org (this month) - sorry for the wait

**Comment by CaptainN** [comment]
@raix Everything you do (and have done) is appreciated.

**Comment by StorytellerCZ** [comment]
We have the team ready as well: https://github.com/orgs/Meteor-Community-Packages/teams/databases

**Comment by StorytellerCZ** [comment]
@raix any update on the move?
