### ISSUE TITLE
New package for inclusion - meteor-typings

### ISSUE THREAD

**Issue by mitar** [Meteor-Community-Packages/organization#36]
This is a meta discussion about [meteor-typings](https://github.com/meteor-typings) organization. It seems it contains some useful typing for various package, but I do not see many updates. Moreover, if they are not kept in sync with package development, they are not very useful.

So maybe we should move all of them here as well? Or even integrate them with packages themselves? Not sure what is best practice here, bundling typings in the same repository or a separate repository?

cc @exKAZUu

**Comment by StorytellerCZ** [comment]
I like the idea. I think where possible we should bundle the typings into the package which would make it a less of a hustle to manage in the long run (not to mention if/when Typescript rewrite comes part of the work is already done).

**Comment by exKAZUu** [comment]
I agree that we should move them here. How do you think, @barbatus, the owner of the repos.

**Comment by copleykj** [comment]
I'm gonna close this for now as the NPM module, `typings`, that these rely on has been deprecated in favor of `@types`.
