### ISSUE TITLE
New package for inclusion - (monitoring) kadira-apm-client

### ISSUE THREAD

**Issue by afrokick** [Meteor-Community-Packages/organization#38]
## Kadira APM client

This library collects client/server data and send it to APM server. Based on [lmachens:kadira](https://github.com/lmachens/kadira) fork of [meteorhacks:kadira](https://github.com/meteorhacks/kadira).

## Links
* [Atmosphere](https://atmospherejs.com/afrokick/kadira)
* [Github repository](https://github.com/afrokick/kadira)

## Current status of the project
- [ ] Active
- [ ] Maintained
- [x] Abandoned

 ## Reasoning
The root of library is meteorhacks:kadira, abandoned with the leave of Arunoda. I have a fork where fixed issues for new version of meteor 1.8.1, refactored to es6.
 
 ## Progress
 - [ ] Discussion finished
 - [ ] Moved / Forked
 - [ ] Team Created
 - [ ] Meteor Org Created and set as maintainer
 - [ ] `communitypackages` org added as a maintainer on Atmosphere

**Comment by zodern** [comment]
[montiapm:agent](https://github.com/monti-apm/monti-apm-agent) is a maintained fork of meteorhacks:kadira. I have been careful to avoid breaking compatibility with Kadira, though Kadira would have to be updated to benefit from some of the improvements.

**Comment by afrokick** [comment]
@zodern thanks!

**Comment by SimonSimCity** [comment]
I'm a bit late here, but I think it's worth mentioning that there's also a package for monitoring using an ELK stack - which might be something you want to use anyways if you're managing the infrastructure yourself - but can equally easy be used for a hosted solution: https://github.com/kschingiz/meteor-elastic-apm
