### ISSUE TITLE
New package for inclusion - meteor-desktop

### ISSUE THREAD

**Issue by KoenLav** [Meteor-Community-Packages/organization#39]
Build desktop apps with Meteor & Electron. Full integration with hot code push implementation.

## Links
* https://github.com/wojtkowiak/meteor-desktop

## Current status of the project
 * Abandoned?

 ## Reasoning
This integration enables building desktop applications for Meteor, just like the Cordova integration enables building mobile applications.

The package combines pre-existing solutions for packaging Electron together with web frameworks. It is loosely coupled with Meteor, modular and well written, so it should be easy to maintain.

We are using this project in production on a large scale and are willing to put in the time to maintain this package. Judging from the open pull requests I think there will be others interested as well.
 
 ## Progress
 - [x] Discussion finished
 - [x] Moved / Forked
 - [x] Team Created
 - [x] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere

**Comment by StorytellerCZ** [comment]
I really like the idea, but prefer to transfer this to core Meteor. :rofl: 
Let's postpone this till we have a better idea where Tiny plans to go with Meteor.

**Comment by Ajaay** [comment]
We are using this in a production app also and would be prepared to help out with this.

**Comment by jamesgibson14** [comment]
I am just looking into using Electron with Meteor, so this package being updated would be great. I will help out as much as I can.

**Comment by StorytellerCZ** [comment]
@wojtkowiak Any official statement?

**Comment by wildhart** [comment]
I also use meteor-desktop in production so would be happy to help maintain the package.

**Comment by KoenLav** [comment]
Seems @wojtkowiak has been vacant in the repository since January, while Electron is picking up the pace with breaking changes.

Just created this PR to fix an issue while running with Node.js 14: https://github.com/wojtkowiak/meteor-desktop/pull/285

Maybe we should simply fork the repository, start working on it, and ask @wojtkowiak to transfer the npm package?

**Comment by KoenLav** [comment]
@StorytellerCZ could this be re-opened?

**Comment by copleykj** [comment]
> Maybe we should simply fork the repository, start working on it, and ask @wojtkowiak to transfer the npm package?

I think this should be fine.

**Comment by harryadel** [comment]
Since @wojtkowiak isn't responding, @KoenLav move your fork under Meteor community packages umbrella and @StorytellerCZ can setup a team that includes you and @Ajaay @jamesgibson14. What do you guys think?

**Comment by dorandeluz** [comment]
Our company also is using meteor-desktop in production and we would be happy to help. This package is key for us and bringing it into Meteor Community would make much sense to us. @KoenLav @StorytellerCZ any update? If this is happening feel free to add me to the team.

**Comment by KoenLav** [comment]
@all I'm sorry this took so long, but basically meteor-desktop has been working fine for a long time for quite a few Electron version, so I didn't see the rush.

@harryadel setting up a team would be great.

@StorytellerCZ could you setup a team with @Ajaay , @dorandeluz and me?

@jamesgibson14 are you still interested in helping out/working on this?

@darqs would you also like to be included?

@wojtkowiak just another ping to make sure you're aware we're moving ahead with this :)

**Comment by StorytellerCZ** [comment]
@KoenLav Done!

**Comment by KoenLav** [comment]
@StorytellerCZ I'm thinking maybe we should also add @wojtkowiak so when/if he returns to the project he can choose to work on it from within Meteor Community Packages (instead of having to request to be added to the team first)?

**Comment by copleykj** [comment]
Ok, since we haven't had any contact from @wojtkowiak, we will just move forward with a fork. @StorytellerCZ can you set up anything that's necessary with NPM?

@KoenLav do you have any time to allocate to this?

**Comment by KoenLav** [comment]
I actually already forked the package a while ago and gave the team access:

https://github.com/Meteor-Community-Packages/meteor-desktop

I haven't made any changes yet, because for us (up until Electron 11) it has been working fine (as long as you set enableRemoteModule to true).

Feel free to raise issues in the repository; I guess we should try and work out how we can get this to work with Electron 12.

**Comment by copleykj** [comment]
Thanks for the update @KoenLav. I've also invited @a4xrbj1 to join this org and the `meteor-desktop` team. Hopefully we can get some PR's rolling and release an update in the near future.

I've also created the #meteor-desktop channel on the slack worspace to facilitate any discussion about the package the doesn't fit into an issue.

**Comment by copleykj** [comment]
I think this should be in order at this point. If there is anything further that is needed, feel free to contact me in slack or by email.
