### ISSUE TITLE
Feature Request repository 

### ISSUE THREAD

**Issue by KoenLav** [Meteor-Community-Packages/organization#4]
I'd like to suggest moving the Meteor feature requests repository over to this organization.

Could we consider renaming this organization to "Meteor Community", without "Packages"?

Thoughts about both suggestions?

**Comment by StorytellerCZ** [comment]
I think feature requests are fine where they are. I think it would be an overreach here.

As for shortening the name, I'm for it.

**Comment by TechplexEngineer** [comment]
MCP(Meteor-Community-Packages) is a nice TLA (three letter acronym) that can be used on Atmosphere `MCP:<package>`

**Comment by KoenLav** [comment]
Thanks for the feedback!

Since there doesn't seem to be major support, and Meteor has found new shepherds, I think we can close this.
