### ISSUE TITLE
New package for inclusion - Meteor-elastic-apm

### ISSUE THREAD

**Issue by kschingiz** [Meteor-Community-Packages/organization#42]
## Links
* [Atmosphere](https://atmospherejs.com/kschingiz/meteor-elastic-apm)
* [Github repository](https://github.com/kschingiz/meteor-elastic-apm)

## Current status of the project
 * Maintained
Somehow maintained

 ## Reasoning
The package is really useful to find performance bottlenecks in your project. Unfortunately I don't have enough time to maintain it, we need bugs to be resolved and we need new features. I can join development after I find some free time to maintain it, but currently can't.
I want community to take over the package, hope we will make the apm which awesome Meteor community deserves.
 
 ## Progress
 - [x] Discussion finished
 - [x] Moved / Forked
 - [x] Team Created
 - [x] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere

**Comment by SimonSimCity** [comment]
I would also opt in as a maintainer, since we're relying on this plugin as a replacement for `kadira`.

**Comment by StorytellerCZ** [comment]
Together with #37 this sounds like a call for an Analytics team to be established if we move forward here...

**Comment by SimonSimCity** [comment]
What's the status here? I'm happy to join such a team! The author of this package even created another package which could be used as a shared package for gathering analytics data to be used as a shared, common way to collect them. There could then be other plugins who extend this one in passing the data on to a system which will store and visualize them. https://github.com/kschingiz/meteor-measured

**Comment by copleykj** [comment]
We can move forward with this if someone is willing to take the lead in getting everything moved and setup. I definitely agree with @StorytellerCZ that establishing an analytics team might be ideal here.

**Comment by copleykj** [comment]
The analytics team is now in place. @kschingiz I've sent you an invite. Once you accept you should then be able to transfer ownership. Then you'll just need to add communitypackages as a maintainer and we can proceed from there.

**Comment by kschingiz** [comment]
@copleykj hi, accepted your invite, thanks! transferred repository to Meteor Community and added maintainer `communitypackages`.
Will be happy to help building analytics, apm, monitoring tools

**Comment by copleykj** [comment]
Great, I'll get the Meteor org set up, and the repository added to the team shortly and then we should be well underway.

**Comment by copleykj** [comment]
This should be all set, so I'll leave you guys to it! I doubt you will, but if you need anything from me, don't hesitate to reach out.
