### ISSUE TITLE
New package for inclusion - herteby:denormalize

### ISSUE THREAD

**Issue by copleykj** [Meteor-Community-Packages/organization#44]
## herteby:denormalize
Simple denormalization for Meteor

## Links
* [Atmosphere](https://atmospherejs.com/herteby/denormalize)
* [Github repository](https://github.com/Herteby/denormalize)

## Current status of the project
 * Abandoned - Looking for maintainers: https://github.com/Herteby/denormalize/issues/21

 ## Reasoning
This package is used by `cultofcoders:grapher` which I believe to be the current best way to set up a well structured performant API setup on top of Meteor's data layer.
 
 ## Progress
 - [x] Discussion finished
 - [x] Moved / Forked
 - [x] Team Created
 - [x] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere

**Comment by evolross** [comment]
One a quick look this seems like a less feature-filled version of [cultofcoders:grapher](https://github.com/cult-of-coders/grapher)?

**Comment by copleykj** [comment]
Actually grapher uses this package under the hood.

**Comment by copleykj** [comment]
Any further thoughts on this?

**Comment by StorytellerCZ** [comment]
I would like to hear from @theodorDiaconu if possible. Primarily if there are any plans from their side with this package. Given that grapher uses it I'm for inclusion.

**Comment by Floriferous** [comment]
@evolross It's very different from grapher. It caches data directly in the other collection that you link, duplicating it between the 2 collections. And the "hard" part is to keep everything nicely in sync :)

Say you have `users` and `userSettings`:

```js
user = {
  _id: 'user1',
  firstName: 'John',
}

userSettings = {
  userId: 'user1',
  language: 'en-US'
  darkMode: true,
}
```

You can cache one collection into another:
```js
Users.cache({
  type: 'one',
  collection: UserSettings,
  fields: ['language'],
  referenceField: 'userId',
  cacheField: 'userSettingsCache'
})

// Turns your users into this in mongoDB
user = {
  _id: 'user1',
  firstName: 'John',
  userSettingsCache: { language: 'en-US' }
}

// And now you can do this wild query:
Meteor.users.find({ 'userSettingsCache.language': 'en-US' })
```

Even though you only update the `UserSettings` collection. So this package is really useful outside of grapher too :)

We use it all over the place to allow us to query our DB in all sorts of ways, including with the awesome [recursive caches](https://github.com/Herteby/denormalize#recursive-caching) :)

**Comment by mitar** [comment]
Lol, I didn't even know about this project. There is mine much older (and it seems with more stars as well), still maintained: https://github.com/peerlibrary/meteor-peerdb

**Comment by Floriferous** [comment]
Indeed, quite similar, though peerDB has much more functionality!

I came across your package a few times, gotta admit, the coffeescript examples always scare me away ! :)

**Comment by mitar** [comment]
Yea, never had the time to convert them. PRs welcome. :-) You can [see JavaScript example here](https://github.com/peer/doc/blob/devel/lib/documents/comment.js#L8).

**Comment by vparpoil** [comment]
Can we move forward for the inclusion of this package @copleykj ?

**Comment by copleykj** [comment]
Like @StorytellerCZ mentioned, I too would like to see what @theodorDiaconu's thoughts are since grapher relies on it for some it's functionality. We will definitely move forward with this if there isn't any outside interest in maintaining it though.

**Comment by theodorDiaconu** [comment]
I think it's great if we can include it, and I can make sure Grapher keeps up with it when it comes to breaking changes.

**Comment by Herteby** [comment]
Hi! Good that it's getting a new caretaker :slightly_smiling_face: Let me know if you need help with something, and when you're done I can mark my package as deprecated and link to the new one.

**Comment by copleykj** [comment]
@Herteby do you prefer us to fork and publish under another namespace? Ideally you could transfer the repo to this org, and then add communitypackages as a maintainer of the package using the meteor cli. This would allow us to continue to update the package under it's current published namespace and cause minimal disruption to those currently using the package. Ultimately though, it's up to you and we will proceed in whichever way you prefer.

**Comment by copleykj** [comment]
ping @Herteby

**Comment by StorytellerCZ** [comment]
ping @Herteby

**Comment by donstephan** [comment]
Any updates? Causing package version issues with Grapher with the release of 2.3. See issue https://github.com/cult-of-coders/grapher/issues/452.

**Comment by StorytellerCZ** [comment]
We need help from @Herteby to get things moving. Would love to get this done.

**Comment by mfen** [comment]
>  Ideally you could transfer the repo to this org, and then add communitypackages as a maintainer of the package using the meteor cli. This would allow us to continue to update the package under it's current published namespace and cause minimal disruption

Any word from @Herteby on this? We're also waiting on this to upgrade some of our apps to Meteor 2.3+.

**Comment by StorytellerCZ** [comment]
I have placed the package under the utilities team. We can create a sub-team later on. With that the transfer is done.

**Comment by StorytellerCZ** [comment]
The only thing remaining would be to add it the website listing.
