### ISSUE TITLE
New package for inclusion - peppelg:bootstrap-3-modal

### ISSUE THREAD

**Issue by distalx** [Meteor-Community-Packages/organization#45]
### peppelg:bootstrap-3-modal

A Meteor package making it easy to use bootstrap 3 modals in Meteor.

### Links
[Atmosphere](https://atmospherejs.com/peppelg/bootstrap-3-modal)
[Github repository](https://github.com/PeppeL-G/bootstrap-3-modal/)

### Current status of the project
Abandoned 

### Reasoning :
This package also work with bootstrap v4. dependancies needs to be updated.

### Progress

- [x]  Discussion finished
- [ ]  Moved / Forked
- [ ]  Team Created
- [ ]  Meteor Org Created and set as maintainer
- [ ]  communitypackages org added as a maintainer on Atmosphere

**Comment by copleykj** [comment]
Does this rely on twbs:bootstrap to function?

**Comment by coagmano** [comment]
Doesn't look like it at first glace. 
Looks like it requires Bootstrap 3 to be loaded, but is agnostic about where it should come from

**Comment by copleykj** [comment]
Ok, Does anyone else want to weigh in on this?

**Comment by namenotrequired** [comment]
> dependancies needs to be updated

I would like this too.

A bonus would be the chance to fix a bug in the original, where you cannot close a modal and open another immediately after

**Comment by StorytellerCZ** [comment]
I'm concerned about long term sustainability of this.
First of, are there devs who can transfer this and at least fix the existing bugs?
Is there interest in further developing this package to keep up with newer Bootstrap releases?
I guess this would go under the existing @Meteor-Community-Packages/blaze

**Comment by jankapunkt** [comment]
with v7.0.0 BS3 is optional and not included by default anymore (@pouya-eghbali hosts the extracted templates on his namespace) It should be not of an issue to reference to working packages for BS3 in order to show some legacy support.

**Comment by StorytellerCZ** [comment]
@distalx @namenotrequired if you can get the permission from the owner then I'm fine moving this under the Blaze team.

**Comment by namenotrequired** [comment]
I ended up forking my own version because I realized my needs were different from those of @distalx, I am not using bootstrap 4, my bad.

**Comment by jankapunkt** [comment]
Maybe I can put this into a different direction - how about making this package a wrapper, being mostly indepent from the Bootstrap version? BS3 is only getting security fixes and BS5 is coming soon. 3 to 5 have each different structures and class names for their components. Abstracting the general modal functionality by at the same time allowing the developer to define the layout may be the way to go here? Disclaimer: I did not use the package but I think this issue refers to many packages, targeting specific Bootstrap versions.

**Comment by jankapunkt** [comment]
I think this should reopen

**Comment by jankapunkt** [comment]
Silence, stalebot 😅

**Comment by copleykj** [comment]
@jankapunkt Feel free to move forward with this if you feel like taking lead on the package.

**Comment by StorytellerCZ** [comment]
I like the idea of @jankapunkt on how to approach this. In that case probably starting from scratch might be a better approach?
