### ISSUE TITLE
New package for inclusion - qualia:profile

### ISSUE THREAD

**Issue by sebakerckhof** [Meteor-Community-Packages/organization#46]
## Package/project name & description
qualia:profile - exports v8 profiles for builds/server startup/runtime

## Links
* [Github repository](https://github.com/qualialabs/profile)
* [Atmosphere](https://atmospherejs.com/qualia/profile)

## Current status of the project
 * Abandoned

 ## Reasoning
I have a PR to make it work under node 12 / meteor 1.9.
I've been actively trying to get in touch with veered about this, but I got no sign of life for months now. So I think we should publish it under MCP.
I'm willing to maintain it, which basically means keep it updated with new node versions.

 ## Progress
 - [x] Discussion finished
 - [ ] Moved / Forked
 - [x] [Team Created](https://github.com/orgs/Meteor-Community-Packages/teams/profiling)
 - [ ] Meteor Org Created and set as maintainer
 - [ ] `communitypackages` org added as a maintainer on Atmosphere

**Comment by SimonSimCity** [comment]
Link to the repo: https://github.com/qualialabs/profile 😅

**Comment by sebakerckhof** [comment]
oops, fixed

**Comment by copleykj** [comment]
I have no problem moving forward with this. Since contacting Qualia has failed, we can publish it under the communitypackages org. @sebakerckhof I've added you as a maintainer on that org so you can publish under it.

**Comment by StorytellerCZ** [comment]
@sebakerckhof @copleykj If we are forking, then maybe a better name would be nice. My first thought was that it has something to do with user profile.

**Comment by mitar** [comment]
> Since contacting Qualia has failed

This is really strange. @veered is pretty interested in open sourcing things they have and keeping it maintained.

**Comment by copleykj** [comment]
@mitar I agree, but it does seem that the pull request and multiple pings have gone unanswered. Should we attempt to reach him for another week? If anyone has a more direct way to contact him that would be great.

**Comment by mitar** [comment]
I can send him an e-mail.

**Comment by StorytellerCZ** [comment]
![do-it](https://user-images.githubusercontent.com/1715235/75514399-bdf87080-5a3a-11ea-8798-3849908e966b.gif)

**Comment by mitar** [comment]
Done. :-)

**Comment by copleykj** [comment]
Thanks @mitar

**Comment by veered** [comment]
@sebakerckhof @mitar Sorry for the delay. I'll merge your change this weekend and republish the package.

**Comment by veered** [comment]
I'm also happy to move it over to community ownership if you'd like. I've had less time for open source stuff for a while now 😞

**Comment by copleykj** [comment]
Thanks @veered! @sebakerckhof do you want to take lead on transferring?

**Comment by veered** [comment]
@sebakerckhof Alright merged your PR and republished the package!

**Comment by veered** [comment]
Also, the best place to contact me is the Meteor Community Slack. I'll make sure to check it regularly.

**Comment by sebakerckhof** [comment]
Thanks!

**Comment by copleykj** [comment]
@veered I've sent you an invite to the org. Once you are a member it will allow you to transfer ownership of the repo. After that you'll just need to run `meteor admin maintainers qualia:profile --add communitypackages` and then I can take care of the rest.

**Comment by copleykj** [comment]
@veered ping :slightly_smiling_face:

**Comment by veered** [comment]
@sebakerckhof Done!
