### ISSUE TITLE
New package for inclusion - adornis:typescript

### ISSUE THREAD

**Issue by perbergland** [Meteor-Community-Packages/organization#47]
## Package/project name & description

adornis:typescript (including the supporting adornis:typescript-compiler) is a typescript compiler package forked from the abandoned barbatus:typescript

It adds a proper Typescript compilation step to the meteor build system.

## Links
* [Atmosphere](https://atmospherejs.com/adornis/typescript)
* [Github repository](https://www.github.com/adornis/typescript)

## Current status of the project

 * Abandoned (can’t reach owner since February 2020)

 ## Reasoning

It provides a different take on Typescript compared to the builtin package for people who prefer the typescript compilation to be an integral part of the build process and want more control over settings.
Its internal code is unfortunately not easy to grasp and probably relies on intimate knowledge about the meteor build system (something I lack).

I could take it on for now. The current owner has given me contribution rights to the two repos so I can also add pointers to the community-owned packages once the move is complete.

The work over the last years have mostly been to upgrade the built-in typescript dependency.
 
 ## Progress
 - [ ] Discussion finished
 - [ ] Moved / Forked
 - [ ] Team Created
 - [ ] Meteor Org Created and set as maintainer
 - [ ] `communitypackages` org added as a maintainer on Atmosphere

**Comment by coagmano** [comment]
I think we'd be better off adding the one missing feature (`tsconfig` support) to the official typescript package, instead of maintaining this one.
Unless this one does something else you need that the official one can't?

context:
https://github.com/Adornis/typescript/issues/25

**Comment by perbergland** [comment]
Reporting and acting on typescript warnings and errors as part of the build process is the showstopper for me. I don't fully understand why it isn't like that already - the author surely understands the intricacies of the meteor build system and still chose to not plug into it properly -  but the only suggestions I've seen is to set up a separate process with the tsc compiler to show errors/warnings.

That doesn't translate so well to build servers, for instance, if you want them to fail a build if there are type errors.

**Comment by coagmano** [comment]
>That doesn't translate so well to build servers, for instance, if you want them to fail a build if there are type errors. 
I find this a pretty persuasive use case.

**Comment by StorytellerCZ** [comment]
Wouldn't a better option be to improve the official Typescript package?

**Comment by perbergland** [comment]
It looks to me like there is not a lot of support from the meteor maintainers to move the meteor TS plugin in the direction requested by https://github.com/meteor/meteor/issues/10939 and I have no idea if it’s possible for outsiders to influence the direction or fork the internal plugin and make it external instead so we can get some progress. Hence the request to make this old and painfully slow plugin a community plugin.

I guess I will have to republish it under my own name in the meantime.

**Comment by perbergland** [comment]
My limited understanding is that by relying on babel for typescript compilation, it’s not possible to get the built in compilation to be part of the build process because according to the babel spec:

Keep in mind that Babel **doesn't do type checking**

https://babeljs.io/docs/en/

**Comment by StorytellerCZ** [comment]
https://forums.meteor.com/t/ann-new-meteor-typescript-package-under-development/52863

**Comment by perbergland** [comment]
There's really no future for that package - withdrawing the request
