### ISSUE TITLE
New package for inclusion - meteor-typescript

### ISSUE THREAD

**Issue by perbergland** [Meteor-Community-Packages/organization#48]
## Package/project name & description

meteor-typescript

A fast Typescript Meteor compiler package with configuration support, incremental compilation and diagnostics output.

## Links
* [Atmosphere](https://atmospherejs.com/refapp/meteor-typescript)
* [Github repository](https://www.github.com/ref-app/meteor-typescript)

## Current status of the project
 * Active

 ## Reasoning
This is a brand new Typescript compiler package that I claim has the best union of features between the core, babel-based compiler and derivates of the old barbatus:typescript.
In my opinion, this should become the #1 choice for all Meteor Typescript developers and maybe should find itself in the core platform once it has matured.
 
 ## Progress
 - [x] Discussion finished
 - [x] Moved / Forked
 - [x] Team Created
 - [x] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere

**Comment by perbergland** [comment]
Here's the annotated "Areas for improvement" list from https://atmospherejs.com/meteor/typescript:

## Areas for improvement

* **CHECK** Compile all TypeScript modules at the same time, rather than compiling
  them individually, to enable cross-module analysis and compilation. In
  the meantime, if you need this behavior, consider using
  [`adornis:typescript`](https://atmospherejs.com/adornis/typescript).

* Use the version of `typescript` installed in the application
  `node_modules` directory, rather than the one bundled with
  `meteor-babel`. We will attempt to keep `meteor-babel`'s version of
  `typescript` up-to-date, but it would be better to leave this decision
  to the application developer.

* Generate `.d.ts` declaration files that can be consumed by external
  tools. In particular, a Meteor package that uses TypeScript could
  generate `.d.ts` files in the `/node_modules/meteor/package-name/`
  directory, which would allow tools like VSCode to find the right types
  for the package when importing from `meteor/package-name`.

* **CHECK** Cache the output of the TypeScript compiler separately from the output
  of Meteor's Babel compiler pipeline. The TypeScript compiler does not
  compile code differently for different targets (server, modern, legacy,
  etc.), so its results could theoretically be reused for all targets.

* **CHECK** Make the `typescript` plugin look up `tsconfig.json` files (similar to
  how `babel-compiler` looks up `.babelrc` files) and obey (some of) the
  configuration options.

**Comment by MastroLindus** [comment]
Awesome work @perbergland !
Unfortunately I have really limited experience with the internals of the building of meteor, babel and typescript, and work is currently leaving me absolutely 0 free time, but if I will see the chance to contribute I will surely do!
Meanwhile a big thank you for your contribution, I am going to surely test the plugin tomorrow!

**Comment by MastroLindus** [comment]
Quick question: in order to test it properly it would be convenient if the typescript version would be at least the official one (3.8.3), if not the latest stable. I could test with a few reasonable sized projects, but they won't compile properly below 3.8.

**Comment by perbergland** [comment]
Well I built and tested with ts 3.9.2 which was released last week

**Comment by MastroLindus** [comment]
strange, i quickly tried installing and running it and i read 3.7.6?
ill check again tomorrow if i did something wrong

**Comment by MastroLindus** [comment]
my bad, I got confused because apparently the plugin installs the meteor typescript package (3.7.6), but it is running 3.9.2 indeed.

To avoid confusion maybe I would output the ts compiler's version like the adornis plugin was doing.

I will anyway test it today and let you know how it goes!

**Comment by perbergland** [comment]
I just published a new version 0.1.0 that outputs the Typescript version it uses

**Comment by perbergland** [comment]
And I would have preferred not to have the core typescript package as a transitive dependency but AFAIK the Meteor package management doesn’t have the concept of devDependencies.

**Comment by MastroLindus** [comment]
Amazing work so far!
Since this issue for the inclusion in the community package, I opened a separate issue in the compiler's github. Thank you again for your work!

**Comment by perbergland** [comment]
Any update here? Can the package become community-owned?

**Comment by copleykj** [comment]
I'm personally ok with this as long as you are on board as the main maintainer, at least for the time being until others can familiarize themselves with the codebase. Does anyone else want to weigh in on this?

**Comment by perbergland** [comment]
Yes I can take on being the main maintainer - does it involve doing anything more than I do now?

**Comment by copleykj** [comment]
@perbergland not at all. Nothing should change except the fact that eventually when others are familiar with the codebase you can do less and they can keep things rolling.

**Comment by copleykj** [comment]
@perbergland I've sent you an invite for the Org. Feel free to transfer the repo and add communitypackages as a maintainer, and I can handle the other minor things after that.

**Comment by perbergland** [comment]
Hi Kelly,

The repos have been moved but I couldn’t find any "communitypackages"
user/team to add as a maintainer.

/Per

Den sön 16 aug. 2020 kl 07:07 skrev Kelly Copley <notifications@github.com>:

**Comment by copleykj** [comment]
Great! communitypackages can be added as a maintainer by running the following commands:

```sh
meteor admin maintainers refapp:typescript --add communitypackages
```

```sh
meteor admin maintainers refapp:typescript-compiler --add communitypackages
```

**Comment by perbergland** [comment]
Ah I thought you were referring to Github permissions.

I've added communitypackages now to the two packages (
*refapp:meteor-typescript* and *refapp:meteor-typescript-compiler* -
refapp:typescript was just a fork of adornis).
Should the packages also be put under a new atmosphere namespace?

/Per



Den mån 17 aug. 2020 kl 15:55 skrev Kelly Copley <notifications@github.com>:

**Comment by copleykj** [comment]
Honestly that is up to you as the original package author. Either way is perfectly fine. If you decide that you want to do that, then we can publish them under the communitypackages org and set the old packages as unmigrated.

**Comment by StorytellerCZ** [comment]
I have added the teams to the Typescript packages in the org. I believe this was the last step, so closing the issue.
:tada:
