### ISSUE TITLE
New package for inclusion - juliancwirko:postcss

### ISSUE THREAD

**Issue by hexsprite** [Meteor-Community-Packages/organization#49]
## Links
* [Atmosphere](https://atmospherejs.com/juliancwirko/postcss)
* [Github repository](https://github.com/juliancwirko/meteor-postcss)

## Current status of the project
 * Abandoned

 ## Reasoning

I forked this package recently (as hexsprite:postcss) so I could update the dependencies and improve some error reporting.

Someone on the Meteor Slack asked about including this in the Meteor Guide and it occurred to me that this package should be community maintained.

 ## Progress
 - [x] Discussion finished
 - [x] Moved / Forked
 - [x] Team Created
 - [x] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere

**Comment by hexsprite** [comment]
There's also the issue that this package may not be needed in the long run if Meteor was to expose PostCSS configuration as a core feature. Internally Meteor uses PostCSS but doesn't make it possible to tweak the config thereby requiring an external package.

**Comment by copleykj** [comment]
What are the chances of this being exposed? Is there an open pull request?

**Comment by hexsprite** [comment]
No PRs at the moment.

**Comment by copleykj** [comment]
Do you have an idea how how much work it would be to expose this? I think since it's already in use internally, it might make more sense to work on making it configurable in core. I'm sure @filipenevola would be more than happy to merge the functionality.

**Comment by hexsprite** [comment]
it's beyond what I have time for now right now. Just seem to recall some commit notes when it was initially merged that it's there somewhere.

**Comment by copleykj** [comment]
I think this is definitely a good fit for community maintenance, especially with the popularity of Tailwindcss and Its use in Packosphere. I'll file an issue and see if we can get it transfered.

**Comment by copleykj** [comment]
Moving this package is now completed. If anyone wishes to help with this package, please let me know.
