### ISSUE TITLE
New package for inclusion - meteorhacks:picker

### ISSUE THREAD

**Issue by StorytellerCZ** [Meteor-Community-Packages/organization#50]
## Package/project name & description
Picker is an easy to use server side router for Meteor. This router respect others. So, you can use Iron Router and other routers and middlewares along side with this.

## Links
* [Atmosphere](https://atmospherejs.com/meteorhacks/picker)
* [Github repository](https://github.com/meteorhacks/picker/)

## Current status of the project

 * Abandoned

 ## Reasoning

It is especially useful when you want to establish server only routes while using things like `react-router`. It is used by many Meteor SSR related projects.
I have modernized it and I'm ready to help maintain it. https://github.com/StorytellerCZ/picker
 
 ## Progress
 - [x] Discussion finished ([issue in Picker](https://github.com/meteorhacks/picker/issues/55))
 - [x] Moved / Forked
 - [x] Team Created
 - [x] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere

**Comment by StorytellerCZ** [comment]
Since Arunoda is not reacting for 2 months or on any other of his Meteor related work I suggest that we move forward and I'll transfer my current form to the MCP org which we can then publish on Atmosphere. Not the best solution, but it will have to do.

**Comment by jankapunkt** [comment]
Wasn't there a post in the forums where Arunode replied not that long ago? Maybe we can follow up there and ask him to transfer his package(s) to MCP?

**Comment by vparpoil** [comment]
I just pinged him in Twitter : https://twitter.com/VictorParpoil/status/1301053213660139520
It would be great to transfer it so we can keep the package name

**Comment by StorytellerCZ** [comment]
For that matter if Arunoda was willing to transfer more packages that people have been requesting that would be awesome, but I'm working on the assumption that Arunoda is currently not interested in any activity around Meteor beyond some basic news.

**Comment by vparpoil** [comment]
Well I guess you should just move forward with transferring your repo to MCP !

**Comment by StorytellerCZ** [comment]
Moved the repository and rebrand `react-router-ssr` team to just `routers`.

**Comment by StorytellerCZ** [comment]
https://github.com/Meteor-Community-Packages/picker
Just making namespace adjustments and will soon publish v1.1.0 to Galaxy.

**Comment by StorytellerCZ** [comment]
The process is now complete: https://atmospherejs.com/communitypackages/picker
