### ISSUE TITLE
New package for inclusion - vsivsi / meteor-file-collection

### ISSUE THREAD

**Issue by juliomac** [Meteor-Community-Packages/organization#51]
## Links
* [Atmosphere](https://atmospherejs.com/vsivsi/file-collection)
* [Github repository](https://github.com/vsivsi/meteor-file-collection)

## Current status of the project

 * Abandoned

 ## Reasoning
This Package has been installed almost 12.000 times. It is the only package that allows using gridFS for file storage (pictures and movies) in an easy and secure way after the demise of the complex fs:collection. The alternative [https://github.com/VeliovGroup/Meteor-Files](url) is not as an elegant solution for grids as this one is.

It is so popular that It has already been forked many times to replace the older coffescript dependency, like done here [https://github.com/brucejo75/meteor-file-collection](url) and here with an non-coffee version [https://github.com/swiftcourt/meteor-file-collection](url).

The other problem is its incompatibility with SSL mongo servers, which is an impediment for using Mongo Atlas, for instance, as detailed here [https://forums.meteor.com/t/issues-migrating-from-mlab-to-atlas/54206](url)  that were supposedly solved here [https://github.com/sakeena12/meteor-file-collection](url). 
  
 ## Progress
 - [ ] Discussion finished
 - [ ] Moved / Forked
 - [ ] Team Created
 - [ ] Meteor Org Created and set as maintainer
 - [ ] `communitypackages` org added as a maintainer on Atmosphere

**Comment by mitar** [comment]
See: https://github.com/Meteor-Community-Packages/organization/issues/33

**Comment by mitar** [comment]
Maybe we should close this issue and make a comment there?

**Comment by copleykj** [comment]
Reopening #33
