### ISSUE TITLE
postcss package - which one should we keep?

### ISSUE THREAD

**Issue by filipenevola** [Meteor-Community-Packages/organization#52]
Hi, I found this issue here https://github.com/Meteor-Community-Packages/organization/issues/49 creating an example for https://github.com/meteor/examples for tailwind.

I'm getting these warnings:
```
WARNING: npm peer requirements (for juliancwirko:postcss) not installed:
 - postcss@8.2.7 installed, postcss@^7.0.0 needed
 - postcss-load-config@3.0.1 installed, postcss-load-config@^2.1.0 needed
```

as hexsprite:postcss is still checking dependencies using [juliancwirko:postcss](https://github.com/hexsprite/meteor-postcss/blob/master/plugin/minify-css.js#L14)

I saw that you migrated juliancwirko:postcss to MCP but it seems the changes from @hexsprite are not in the repo here.

I would like to remove these warnings but I don't know where I should make a PR.

**Comment by copleykj** [comment]
As far as I know, the only changes that `hexsprite:postcss` contains are just updated versions to squelch the check versions warnings but it is also behind the current versions of `postcss` and `postcss-load-config` and confusingly states that it is `juliancwirko:postcss`.

All pull requests can be submitted to https://github.com/Meteor-Community-Packages/meteor-postcss. That being said, I should have this issue patched and a release done in the next hour or so.
