### ISSUE TITLE
New package for inclusion - meteortesting:mocha + mocha-core

### ISSUE THREAD

**Issue by perbergland** [Meteor-Community-Packages/organization#57]
## Links
* [Atmosphere](https://atmospherejs.com/meteortesting/mocha)
* [Github repository](https://github.com/meteortesting/meteor-mocha)
* [Project homepage](https://github.com/meteortesting/meteor-mocha)

## Current status of the project
 * Abandoned (last activity Jan 2021)

 ## Reasoning
The primary CI-testing package for Meteor, currently incompatible with 2.3 because of meteor internal package updates (http)
 
 ## Progress
 - [x] Discussion finished
 - [x] Moved / Forked
 - [x] Team Created
 - [x] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere

**Comment by perbergland** [comment]
ping @aldeed just in case it reaches him this time

**Comment by perbergland** [comment]
Finally got in touch with the current maintainers via email and they are onboard with moving the repos 🥳

**Comment by SimonSimCity** [comment]
I'm happy to support with sharing some of the knowledge I have if required. As I see, I've been the most active person on that repo in the past 2 years. I don't have much spare time, but I can share what I know at least if requested.

FYI: I would include the package `meteor-browser-tests` in this group of packages to be moved. It's used by `meteortesting:mocha` and has some open tickets which are needed for some tasks on `meteortesting:mocha`.

**Comment by StorytellerCZ** [comment]
@SimonSimCity isn't `meteor-browser-tests` and official package or under Blaze?

**Comment by aldeed** [comment]
I'm also happy to transfer or help transition these three packages. These are the only 3 repos in the `meteortesting` org, so we can essentially merge that org into this one.

In general I think updating `meteor-browser-tests` to add support for a modern and active framework like Playwright would be a good idea, and dropping support for less maintained drivers. Not sure if I will find time to do this, but throwing it out there.

Not sure who currently needs to approve this transition, but if everyone has signed off let us know so one of us can initiate repo transfers and update org ownership.

**Comment by SimonSimCity** [comment]
@StorytellerCZ `meteor-browser-tests` isn't linked to Blaze, but controls the way the browsers are started to run the client-side tests. Just the question how well something like [`playwright`](https://github.com/microsoft/playwright) would work in an environment without shell or screen - like on most CI envs.

**Comment by StorytellerCZ** [comment]
@aldeed If you could add community packages to the packages admins on Atmosphere and me as an admin in the org I should be able to take it from there.

**Comment by StorytellerCZ** [comment]
Team created: https://github.com/orgs/Meteor-Community-Packages/teams/testing

**Comment by aldeed** [comment]
Lost track of this but I now have a reminder to do it tomorrow when I have more time.

**Comment by aldeed** [comment]
@StorytellerCZ 

- [x] Added you as owner of `meteortesting` GitHub org to initiate transfers
- [x] Added `communitypackages` as maintainer on `meteortesting:mocha-core` Meteor package
- [x] Added `communitypackages` as maintainer on `meteortesting:mocha` Meteor package
- [x] Added `communitypackages` as maintainer on `meteortesting:browser-tests` Meteor package

When all github transfers are complete, you can delete the `meteortesting` GitHub org, or let me know and I will. I don't see any further purpose for it. The `meteortesting` Meteor org could also be deleted but I'm not sure if there is any way to delete them.

cc @SimonSimCity @tmeasday fyi

**Comment by StorytellerCZ** [comment]
@aldeed Thanks a lot for this! I will move on the transfers first thing tomorrow.
We have a team setup here:
@Meteor-Community-Packages/testing

**Comment by StorytellerCZ** [comment]
And completed. I'm going to delete the now empty organization so that there isn't any confusion.
