### ISSUE TITLE
New package for inclusion - aldeed:tabular

### ISSUE THREAD

**Issue by ricaragao** [Meteor-Community-Packages/organization#58]
## Package/project name & description
aldeed:tabular
Datatables for large or small datasets in Meteor

## Links
* [Atmosphere](https://atmospherejs.com/aldeed/tabular)
* [Github repository](https://github.com/longshotlabs/meteor-tabular)
* [Project homepage](https://github.com/longshotlabs/meteor-tabula)

## Current status of the project
 * Abandoned

 ## Reasoning
This package is very useful in many projects and it are more than 5 years without update. I'd like help it.
 
 ## Progress
 - [x] Discussion finished
 - [x] Moved / Forked
 - [ ] Team Created
 - [ ] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere

**Comment by harryadel** [comment]
@aldeed Since you're moving meteortesting:mocha :man_shrugging:

**Comment by aldeed** [comment]
I kinda thought I had passed off maintenance of this one to another person, but it does seem pretty abandoned and I don't see anyone else listed with push access. I'm happy to transfer this one as well. It's probably the most complex thing I ever made so hopefully someone understands it well enough to update and maintain it. 😅

**Comment by StorytellerCZ** [comment]
Do we have enough maintainers? Or is it important to move so that we can publish updates?

**Comment by harryadel** [comment]
You can count me in. I still love tabular and think it's a great package.

**Comment by StorytellerCZ** [comment]
Alright, let's start the process of moving it.

**Comment by aldeed** [comment]
@StorytellerCZ Sorry, took some time off. I'll start transferring.

**Comment by aldeed** [comment]
Initiated GH repo transfer and added `communitypackages` as atmosphere maintainer

**Comment by aldeed** [comment]
Also, unrelated, I noticed this org page on GH has the link https://meteorjs.community/ which isn't working.

**Comment by StorytellerCZ** [comment]
Got the transfer, assigning the Blaze team to it right now and creating a new page on the community website which I'm working on to get back online.
Thanks a lot @aldeed
