### ISSUE TITLE
New package for inclusion - dburles:mongo-collection-instances

### ISSUE THREAD

**Issue by vparpoil** [Meteor-Community-Packages/organization#59]
## dburles:mongo-collection-instances

This package augments Mongo.Collection (and the deprecated Meteor.Collection) and allows you to later lookup a Mongo Collection instance by the collection name.

## Links
* [Atmosphere](https://atmospherejs.com/dburles/mongo-collection-instances)
* [Github repository](https://github.com/dburles/mongo-collection-instances/)

## Current status of the project
 * Abandoned

 ## Reasoning
This package is a dependency of `cultofcoders:grapher` that needs an update because it relies on `lai:collection-extensions@0.2.1_1` which is incompatible with last version of Meteor.

Since `lai:collection-extensions` has moved to MCP and some changes have been made recently by @StorytellerCZ, I think it would be natural to also include `dburles:mongo-collection-instances` and update it's dependency to version 0.3.0 (not yet published, [see here](https://github.com/Meteor-Community-Packages/meteor-collection-extensions/issues/19)) of `lai:collection-extensions`
 
 ## Progress
 - [x] Discussion finished
 - [x] Moved / Forked
 - [x] Team Created
 - [x] Meteor Org Created and set as maintainer
 - [x] `communitypackages` org added as a maintainer on Atmosphere

**Comment by vparpoil** [comment]
This is not stale @stalebot ;)

**Comment by StorytellerCZ** [comment]
With grapher inclusion in MCP, we have to add this as well.

**Comment by StorytellerCZ** [comment]
@dburles agreed to move it over. Starting the process.

**Comment by StorytellerCZ** [comment]
Done!
https://github.com/Meteor-Community-Packages/mongo-collection-instances
