### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by StorytellerCZ** [Meteor-Community-Packages/organization#6]
I have volunteered to manage the newsletter. I have a full account with [Constant Contact ](https://www.constantcontact.com/features/signup.jsp?rc=2007424597&sru=1110108987223&fc=f&cc=RAF-REFLINK&pn=ROVING) so I'm going to use that for now.

I would like to make this an occasional newsletter that will go out under the following circumstances:
* New Meteor release
* Important package has been released
* Important community event happening
* Important articles published

The newsletter would include the following:
* The main news (highlight of the release that triggered the newsletter with a link to article or changelog).
* List of other recent releases of selected packages
* News from the community that we want to communicate (podcast, etc.)
* Interesting articles from the official blog or community members
* Selected topics from the forums

I think a copy editor would be nice to have or someone who could check my English as it is not my first language.

Thoughts?

**Comment by StorytellerCZ** [comment]
With Constant Contact I can have all the newsletters available as a static page. Though I'm imagining newsletter more as a summary and highlights from the other channels. Though how to handle the other media is a good question.

**Comment by jankapunkt** [comment]
> could hit other social media channels - Twitter, Facebook, Medium, ... the list is endless!

Especially https://dev.to/ where Meteor is totally [underrepresented](https://dev.to/search?q=Meteor)

**Comment by StorytellerCZ** [comment]
@jankapunkt That is the first time I heard of dev.to

**Comment by coagmano** [comment]
Happy to help with newsletter as well, I used to do a little bit of email marketing in a past career :)

**Comment by StorytellerCZ** [comment]
@jankapunkt @coagmano I'll try to setup something over the weekend.
Created group on Minds: https://www.minds.com/groups/profile/965536494046842880/feed
Seems to also have some gathering functionality which might be useful for hangouts.
For other social media, I would for now link to the official Meteor accounts for now.

**Comment by StorytellerCZ** [comment]
Sign-up page for newsletter:
https://visitor.r20.constantcontact.com/manage/optin?v=001shuT2XU7mN-a0Jygxugg6iL_JIHP626F8r9WSftJl3VFhfyIaU1Gh9VcoftVTJ0dhkZbe-DQruAH7G8G20yiULC9NPtnssmIELgWAnXIMRY%3D

**Comment by KoenLav** [comment]
Should MDG allow community maintainers in their Medium organization? Nothing has happened over there since 2016.

https://medium.com/@meteorjs

**Comment by robfallows** [comment]
@KoenLav : I'm not sure why that link isn't showing recent posts. If you navigate to the [Meteor blog URI](https://blog.meteor.com/) you will find plenty of articles which are much more recent than 2016.

**Comment by KoenLav** [comment]
@robfallows ah, I see!

Might still be a good idea to ask MDG to allow at least one person involved in the newsletter to post on Medium as well.

**Comment by robfallows** [comment]
MDG have always encouraged community members to write articles for the Meteor blog - unless you're referring to editor, rather than author, rights?

**Comment by KoenLav** [comment]
I don't mind how it's setup, but I guess the desired end-result would be that content which is mentioned in the newsletter is also linked on Medium, using the official MDG account.

**Comment by StorytellerCZ** [comment]
From my point of view, I will focus on content for now. Distribution can be adjusted later once we prove ourselves.

**Comment by alimgafar** [comment]
> > could hit other social media channels - Twitter, Facebook, Medium, ... the list is endless!
> 
> Especially https://dev.to/ where Meteor is totally [underrepresented](https://dev.to/search?q=Meteor)

I didn't know this site existed. How popular is it?

**Comment by alimgafar** [comment]
Jan,
I had a past career as an editor. I have limited time, but can help out if you'd like me to review articles before they're published.

**Comment by jankapunkt** [comment]
> I didn't know this site existed. How popular is it?

I think it is still rather small but very focused on developers. If you want to hit the right target group, there it is.

**Comment by StorytellerCZ** [comment]
@alimgafar That would be awesome! For the most part, I have the newsletter ready for 1.8.2 release. I'm also very busy so I'm preparing things ahead. I will get to it hopefully this weekend.

**Comment by StorytellerCZ** [comment]
Closing as we now have active Slack and the first newsletter went out.
