### ISSUE TITLE
New package for inclusion -twbs:bootstrap

### ISSUE THREAD

**Issue by jankapunkt** [Meteor-Community-Packages/organization#64]
## Links
* [Atmosphere](https://atmospherejs.com/twbs/bootstrap)
* [Github repository](https://github.com/twbs/bootstrap/)

## Current status of the project
The project is active and they even still update the `package.js` file but they don't publish...

 ## Reasoning
We should ask them to hand over the publishing rights and release all versions until today. This should be doable in one day and would help many people, that come from older packages to include bootstrap at ease.
 
 ## Progress
 - [ ] Discussion finished
 - [ ] Moved / Forked
 - [ ] Team Created
 - [ ] Meteor Org Created and set as maintainer
 - [ ] `communitypackages` org added as a maintainer on Atmosphere
 - [ ] Added to the [community website](https://github.com/Meteor-Community-Packages/website) project listings

**Comment by StorytellerCZ** [comment]
The question is if things are still compatible with Meteor and maybe just asking them might get things published. Has anyone asked them directly?

**Comment by jankapunkt** [comment]
Yes they are! It's just publishing the remaining versions. I could ask them to either add us to their group to publish the packages.

**Comment by StorytellerCZ** [comment]
Please do.
