### ISSUE TITLE
sungwoncho:mailman

### ISSUE THREAD

**Issue by juliomac** [Meteor-Community-Packages/organization#65]
## Links
* [Atmosphere](https://atmospherejs.com/sungwoncho/mailman)
* [Github repository](https://github.com/sungwoncho/meteor-mailman)

## Current status of the project
 * Abandoned

 ## Reasoning
It is simple to fix and helps a lot in development.

**Comment by StorytellerCZ** [comment]
It has been a few months, but did not get a reply. So the next step would be to fork it. But before that we need volunteers who are going to take care of it, otherwise I don't want to increase our workload more than it already is.

**Comment by StorytellerCZ** [comment]
Closing as duplicate of #62
