### ISSUE TITLE
Readme.md link to https://www.meteor.com/account-settings redirects to 404 error page

### ISSUE THREAD

**Issue by alimgafar** [Meteor-Community-Packages/organization#66]
In the **TEAMS** section of the readme, the link behind "create it here" points to https://www.meteor.com/account-settings

This link is no longer valid and should be updated. The current one to create an organization is https://cloud.meteor.com/organizations 

You should confirm that this provides the same behavior as the prior link. Confirm that this is in fact correct for this use case and make the appropriate change.

**Comment by StorytellerCZ** [comment]
Yes, that is the page we want. Fixing.
