### ISSUE TITLE
meteorjs.community link opens a blank document.

### ISSUE THREAD

**Issue by alimgafar** [Meteor-Community-Packages/organization#67]
The link does not return a 404 error. It does load a document with empty head and empty body tags. I don't think this is the expected behavior.

using cURL from the command line gives the following:

`curl -v https://meteorjs.community
*   Trying 104.21.60.76:443...
* Connected to meteorjs.community (104.21.60.76) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /Users/alimgafar/anaconda3/ssl/cacert.pem
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: May 11 00:00:00 2022 GMT
*  expire date: May 10 23:59:59 2023 GMT
*  subjectAltName: host "meteorjs.community" matched cert's "meteorjs.community"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: meteorjs.community]
* h2h3 [user-agent: curl/7.82.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x7f9efa00a800)
> GET / HTTP/2
> Host: meteorjs.community
> user-agent: curl/7.82.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200 
< date: Mon, 29 Aug 2022 05:55:08 GMT
< content-type: text/html; charset=utf-8
< last-modified: Mon, 28 Feb 2022 18:03:00 GMT
< access-control-allow-origin: *
< expires: Mon, 29 Aug 2022 06:01:17 GMT
< cache-control: max-age=600
< x-proxy-cache: MISS
< x-github-request-id: 63C2:3F6A:60D359:F5B7E2:630C53D5
< accept-ranges: bytes
< via: 1.1 varnish
< age: 42
< x-served-by: cache-lga21941-LGA
< x-cache: HIT
< x-cache-hits: 1
< x-timer: S1661752508.110994,VS0,VE1
< vary: Accept-Encoding
< x-fastly-request-id: 3ef032cd5082b04b92eb0b5383f97472ce0af95d
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=iAeLfFyQ0gPKQEIH9opxTtMz%2BEokAFmpnfv57i7Z4E4G2Q%2BbVahsTN94fipEgMUHdjuznFg79WLmxlXuKBQJKg1qbpVWj6KSk3Et%2Bco3wKP8BNincTRnvTtI3o2HG%2BEZdGIedQQ%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 742309379e71c3f8-EWR
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
< 
* Connection #0 to host meteorjs.community left intact
`

**Comment by StorytellerCZ** [comment]
As per
