### ISSUE TITLE
Podcast

### ISSUE THREAD

**Issue by StorytellerCZ** [Meteor-Community-Packages/organization#7]
Podcast seemed to be quiet popular in the survey. So let's get things going @distalx . I'm willing to help, but I have very limited time so don't expect much.

First of, I think we should establish a format for the podcasts and then topics to cover in the near future.

**Comment by distalx** [comment]
I don't have any prior experience with podcasting, So planning on taking trial and error approach. 

ATM I have the following two formats in mind for every other week. 

Format 1: where we invite someone from the community and have a conversation with them, currently thinking about keeping the conversation in around following [topic](https://docs.google.com/document/d/15DFgOVLz-QM2C--779Ax-yQIBcmE1erYIMsK2MjwKHs/edit?usp=sharing) (feel free to edit/update the doc).

Format 2: where we provide highlight on current happening things like discussion happing on Github & forum, community update, underrated feature request & stale issues.

I'm thinking about using [zoom](https://zoom.us/) or [zencastr](https://zencastr.com/) for recording conversations. Zoom has a really great audio quality. And perform a basic edit operation with 'Audacity' & published on simplecast or soundcloud. 

I enjoyed listening to [crater](http://podcast.crater.io/) and [transmission](https://transmission.simplecast.fm/), hoping to produce the same kind of quality content.

If anyone here is interested in co-hosting 🎧, Please leave a comment down below.

**Comment by StorytellerCZ** [comment]
@distalx That I want to help goes without saying, though I'm not sure if I'm any good for co-hosting (will have to see how my voice sounds over the air among other things).

**Comment by StorytellerCZ** [comment]
Recently there has been an episode on Syntax.fm: https://syntax.fm/show/270/meteor-s-2nd-life
I'll talk with Scott Tolinski to see what we can do to get something more regular going.
